name: Cleanup Azure deployment

inputs:
  AZURE_TOKEN:
    description: azure token
    required: true

runs:
  using: composite
  steps:
    - name: Close Pull Request
      id: closepullrequest
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.AZURE_TOKEN }}
        action: "close"
        app_location: "/" # App source code path
