name: CI

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies & tooling
        id: setup
        uses: ./.github/workflows/setup

      - run: cp .env.example .env

      - name: Lint
        run: pnpm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies & tooling
        id: setup
        uses: ./.github/workflows/setup

      - run: cp .env.example .env

      - name: Typecheck
        run: pnpm run typecheck

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies & tooling
        id: setup
        uses: ./.github/workflows/setup

      - run: cp .env.example .env

      - name: Format
        run: pnpm run format:check
