name: Deploy Production

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  run_migrations:
    name: Run migrations
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies & tooling
        uses: ./.github/workflows/setup

      - name: Apply Migrations
        run: |
          touch .env
          echo SKIP_ENV_VALIDATION=1 >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          pnpm run db:migrate

  deploy_vercel_production:
    name: Deploy Vercel Production
    runs-on: ubuntu-latest
    environment: production
    needs: run_migrations
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies & tooling
        uses: ./.github/workflows/setup

      - name: Apply Migrations
        run: |
          touch .env
          echo SKIP_ENV_VALIDATION=1 >> .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          pnpm run db:migrate

      - name: Deploy to Production
        uses: ./.github/workflows/cd/vercel/deploy-production
        with:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  # deploy_azure_production:
  #   name: Deploy Azure Production
  #   runs-on: ubuntu-latest
  #   needs: run_migrations
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Install dependencies & tooling
  #       uses: ./.github/workflows/setup

  #     - name: Deploy to Production
  #       uses: ./.github/workflows/cd/azure/deploy-production
  #       with:
  #         AZURE_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SAND_0ABCEB503 }}
  #         DATABASE_URL: ${{ secrets.DATABASE_URL }}
  #         NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
