name: Deploy Preview

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: Setup
    outputs:
      branch: ${{ steps.branch_name.outputs.current_branch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies & tooling
        id: setup
        uses: ./.github/workflows/setup

      - name: Get branch name
        id: branch_name
        uses: tj-actions/branch-names@v8

  ci:
    name: CI checks
    needs: setup
    uses: ./.github/workflows/ci.yml

  deploy_preview:
    name: Deploy Preview
    environment: Preview
    runs-on: ubuntu-latest
    needs: [setup, ci]
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies & tooling
        uses: ./.github/workflows/setup

      - name: Create Neon Branch
        id: create_branch
        uses: neondatabase/create-branch-action@v5
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          # parent: main # optional (defaults to your primary branch)
          branch_name: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          database: neondb
          username: neondb_owner
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Run Migrations
        run: |
          touch .env
          echo SKIP_ENV_VALIDATION=1 >> .env
          echo DATABASE_URL=${{ steps.create_branch.outputs.db_url_with_pooler }} >> .env
          echo DIRECT_URL=${{ steps.create_branch.outputs.db_url }} >> .env
          pnpm run db:migrate

      - name: Post Schema Diff Comment to PR
        uses: neondatabase/schema-diff-action@v1
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          compare_branch: preview/pr-${{ github.event.number }}-${{ needs.setup.outputs.branch }}
          database: neondb
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base_branch: main
          api_key: ${{ secrets.NEON_API_KEY }}

      - name: Deploy to Preview (Vercel)
        id: deploy_vercel
        uses: ./.github/workflows/cd/vercel/deploy-preview
        with:
          VERCEL_TOKEN: ${{ secrets.vercel_token }}

      # - name: Deploy to Preview (Azure)
      #   id: deploy_azure
      #   uses: ./.github/workflows/cd/azure/deploy-preview
      #   with:
      #     AZURE_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_JOLLY_SAND_0ABCEB503 }}
      #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     # Add all necessary env at build and runtime
      #     DATABASE_URL: ${{ steps.create_branch.outputs.db_url_with_pooler }}
      #     NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}

      - name: Comment on Pull Request
        uses: thollander/actions-comment-pull-request@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Vercel Preview URL :rocket: : ${{ steps.deploy_vercel.outputs.preview_url }}
            Neon branch :elephant: : https://console.neon.tech/app/projects/${{ vars.NEON_PROJECT_ID }}/branches/${{ steps.create_branch.outputs.branch_id }}
